os:
  editPreset: "vscode"
promptToReturnFromSubprocess: false
gui:
  language: "ja"
  showIcons: true
  nerdFontsVersion: "3"
git:
  pagers:
    - colorArg: always
      pager: delta --dark --paging=never --side-by-side --line-numbers --hyperlinks --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"
  branchLogCmd: git log --graph --date=short --color=always --pretty=format:"%C(yellow)%h %C(white)%s %C(green)%d %C(red)%cn %C(blue)%cd - %cr" {{branchName}} --
  allBranchesLogCmds:
    - git log --graph --date=short --color=always --pretty=format:"%C(yellow)%h %C(white)%s %C(green)%d %C(red)%cn %C(blue)%cd - %cr" --
