shell = "zsh"

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
tag = "v0.7.1"
use = ["{{ name }}.zsh"]

# Keep syntax highlighting last.
[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"
tag = "0.8.0"
